[package]
authors = ["jiangzhe <zhe.jiang@transwarp.io>"]
edition = "2018"
name = "lms-rs"
version = "0.1.0"

[dependencies]
enum_dispatch = "0.3"
src = "*"
thiserror = "1.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm10-0"] }